### ISSUE TITLE
Не отображается список преподавателей [БАГ]

### ISSUE THREAD

**Issue by Sanya59** [Damego/ETIS-mobile#85]
**Описание бага**
В мобильном приложении не удается получить список преподавателей, хотя на сайте етиса список преподавателей отображается. Етис мобайл выдает ошибку "Нет данных для отображения".

**Воспроизведение бага**

Для инициирования бага достаточно зайти в меню Преподаватели во вкладке Сервисы приложения Етис мобайл.

**Ожидаемое поведение**
Корректное отображение списка преподавателей

**Скриншоты**

![IMG_20230901_190050](https://github.com/Damego/ETIS-mobile/assets/89939087/f85f53b0-5264-42ba-b8c8-8fe487f864b8)
![Screenshot_2023-09-01-18-56-11-861_com damego etismobile](https://github.com/Damego/ETIS-mobile/assets/89939087/1413ba78-886c-491e-8945-9e991f717f2b)

**Версия приложения**
1.1.0

**Информация об устройстве:**

- Название: Xiaomi 11 Lite 5G NE
- Операционная система: MIUI Global 14.0.4 (Android 13)

**Comment by ijo42** [comment]
Здравствуйте, действительно, мы не тестировали приложение на колледж и лицей, т.к. не имеем нужных контактов с такими студентами.

Постараемся как можно скорее выпустить патч для данной ситуации, что бы помочь отладить предлагаю запустить приложение в отладочном режиме, для этого: 
1. полностью закройте ЕТИС мобайл
2. зажмите по иконке приложения до появления шорткатов
3. выберите Отладочный запуск
4. повторите действия, которые приводят к ошибке
после этого нам придут дополнительные отладочные данные

Спасибо за первый репорт, будем рады если и в дальнейшем Вы поможете в адаптации приложения для студентов колледжа!
