### ISSUE TITLE
[БАГ] Преподаватель числится несколько раз в списке

### ISSUE THREAD

**Issue by esperor** [Damego/ETIS-mobile#96]
**Описание бага**

Если преподаватель ведет больше одного предмета, то он будет появлятся в списке несколько раз: по одному для каждого предмета

**Воспроизведение бага**

1. Иметь преподавателя, который ведет два или более предметов в одном триместре
2. Зайти в список преподавателей
3. Увидеть ошибку

**Ожидаемое поведение**

Преподаватель ведет предметы, а не предметы преподавателя (пусть два+ предмета числятся для преподавателя)

**Скриншоты**

![image](https://github.com/Damego/ETIS-mobile/assets/49198951/c0c5feda-ad7d-4ab5-8ae8-b664eb09a6b6)

**Версия приложения**

dev

**Comment by ijo42** [comment]
не баг, а фича
