### ISSUE TITLE
[БАГ] Вложенные элективные предметы

### ISSUE THREAD

**Issue by ijo42** [Damego/ETIS-mobile#99]
**Описание бага**
В некоторых программах возможен выбор не просто элективных дисциплин, но и дважды вложенных
Из-за чего сдвиг происходит с ошибкой и знак "{" считается за название предмета

**Скриншоты**

![image](https://github.com/Damego/ETIS-mobile/assets/53531892/7edca47b-1661-441b-9462-436010dc426f)
![image](https://github.com/Damego/ETIS-mobile/assets/53531892/7aae6124-1ddf-40bf-bc26-9f5f7446ff2e)

**Версия приложения**

1.1.3 - release

**Comment by Damego** [comment]
Гитхаб решил, что закрывать это иссуе не надо, ну да ладно
